name: utmexpress
description: UTM Bus Shuttle Application
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: 'assets/img/UTMExpress-icon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
     - assets/img/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
          style: italic
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/DMSans-MediumItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-BoldItalic.ttf
          style: italic
          weight: 700